services:
  - type: web
    name: client
    env: static
    buildCommand: cd client && npm install --legacy-peer-deps && NODE_OPTIONS=--openssl-legacy-provider CI=false npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: server
          type: web
          property: host
      - key: CI
        value: false
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
      - key: NODE_VERSION
        value: 16.20.0

  - type: web
    name: server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: NODE_VERSION
        value: 16.20.0 