services:
  - type: web
    name: client
    env: docker
    dockerfilePath: ./client/Dockerfile
    buildCommand: docker build -t client-prod -f ./client/Dockerfile .
    startCommand: docker run client-prod
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: server
          property: host
    autoDeploy: true

  - type: web
    name: server
    env: docker
    dockerfilePath: ./server/Dockerfile
    buildCommand: docker build -t server-prod -f ./server/Dockerfile .
    startCommand: docker run server-prod
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false # You'll set this in Render dashboard
    autoDeploy: true 